---
- name: Install PyMySQL
  become: true
  apt:
    name: python3-pymysql
    state: present

- name: Login as root and create client user
  remote_user: ubuntu
  become: true
  become_user: root
  mysql_user:
    check_implicit_admin: yes
    login_user: root
    login_password: ''
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: "{{ lookup('env', 'MARIADB_USER') }}"
    host: '%'
    password: "{{ lookup('env', 'MARIADB_PASSWORD') }}"
    priv: '*.*:ALL,GRANT'
  when: inventory_hostname == 'database_1'

- name: Create a new database with name 'mariondb'
  community.mysql.mysql_db:
    check_implicit_admin: yes
    login_user: "{{ lookup('env', 'MARIADB_USER') }}"
    login_password: "{{ lookup('env', 'MARIADB_PASSWORD') }}"
    name: "{{ lookup('env', 'MARIADB_DATABASE') }}"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock
  when: inventory_hostname == 'database_1'