---
- name: Install PyMySQL
  become: true
  apt:
    name: python3-pymysql
    state: present

- name: Login as root and create client user
  remote_user: ubuntu
  become: true
  become_user: root
  mysql_user:
    check_implicit_admin: yes
    login_user: root
    login_password: ''
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: tryhard
    host: '%'
    password: "1234"
    priv: '*.*:ALL,GRANT'

- name: Create a new database with name 'mariondb'
  community.mysql.mysql_db:
    check_implicit_admin: yes
    login_user: tryhard
    login_password: "1234"
    name: mariondb
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock