---
- hosts: 'mariadb-test'
  become: true
  tasks: 
    - name: Include variables
      ansible.builtin.include_vars:
        file: "../vars/main.yml"

    - name: update package list
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      become: true

    - name: installing pre-reqs
      ansible.builtin.apt:
        name: "{{ mariadb_pre_req_packages }}"
        state: "present"
      become: true
      retries: 10
      delay: 30
      register: result
      until: result is not failed
      loop:

    - name: check for mariadb apt source list
      stat: "path=/etc/apt/sources.list.d/mariadb.list"
      register: mariadb_apt_list_script

    - name: get apt source list setup script
      ansible.builtin.get_url:
        url: "{{ mariadb_apt_list_script_url }}"
        dest: "{{ mariadb_apt_list_script_path }}"
        mode: '0664'
      when: not mariadb_apt_list_script.stat.exists

    - name: run apt source list setup for mariadb-server {{ mariadb_version }}
      become: true
      shell:
        cmd: >-
          bash "{{ mariadb_apt_list_script_path }}"
          --mariadb-server-version=10.7
      when: not mariadb_apt_list_script.stat.exists

    - name: install mariadb-server
      ansible.builtin.apt:
        name: "{{ mariadb_packages }}"
        update_cache: true
      become: true
    
    - name: Install PyMySQL
      become: true
      apt:
        name: python3-pymysql
        state: present

    - name: Login as root and create client user
      remote_user: ubuntu
      become: yes
      become_user: root
      mysql_user:
        check_implicit_admin: yes
        login_user: root
        login_password: ''
        login_unix_socket: /var/run/mysqld/mysqld.sock
        name: client
        host: '%'
        password: 1234
        priv: '*.*:ALL,GRANT'

    - name: Create a new database with name 'mariondb'
      community.mysql.mysql_db:
        check_implicit_admin: yes
        login_user: client
        login_password: 1234
        name: mariondb
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock
