---
all:
  children:
    frontend:
      vars:
        ansible_port: 22
        ansible_user: ubuntu
        ansible_host: 10.0.0.10
        ansible_ssh_common_args: >-
          -o ProxyCommand="ssh -W %h:%p -q ubuntu@13.36.46.172" -o
          StrictHostKeyChecking=no
      children:
        frontend_instance_1:
          hosts:
            frontend_1:
              ansible_host: 10.0.0.10
        frontend_instance_2:
          hosts:
            frontend_2:
              ansible_host: 10.0.32.10
        frontend_instance_3:
          hosts:
            frontend_3:
              ansible_host: 10.0.64.10