all:
  hosts:
    mariadb_database:
      ansible_port: 22
      ansible_user: "ubuntu"
      ansible_host: 10.0.0.30
      ansible_ssh_common_args: >-
        -o ProxyCommand="ssh -W %h:%p -q ubuntu@35.181.111.83" -o
        StrictHostKeyChecking=no
    monitor:
      ansible_port: 22
      ansible_user: ubuntu
      ansible_host: 10.0.0.40
      ansible_ssh_common_args: >-
        -o ProxyCommand="ssh -W %h:%p -q ubuntu@35.181.111.83" -o
        StrictHostKeyChecking=no