---
all:
  children:
    frontend:
      vars:
        ansible_port: 22
        ansible_user: ubuntu
        ansible_ssh_common_args: >-
          -o ProxyCommand="ssh -W %h:%p -q ubuntu@13.36.46.172" -o
          StrictHostKeyChecking=no
      children:
        frontend_instance_1:
          hosts:
            frontend_1:
              ansible_host: 10.0.0.10
        frontend_instance_2:
          hosts:
            frontend_2:
              ansible_host: 10.0.32.10
        frontend_instance_3:
          hosts:
            frontend_3:
              ansible_host: 10.0.64.10
    backend:
      vars:
        ansible_port: 22
        ansible_user: ubuntu
        ansible_ssh_common_args: >-
          -o ProxyCommand="ssh -W %h:%p -q ubuntu@13.36.46.172" -o
          StrictHostKeyChecking=no
      children:
        backend_instance_1:
          hosts:
            backend_1:
              ansible_host: 10.0.0.20
        backend_instance_2:
          hosts:
            backend_2:
              ansible_host: 10.0.32.20
        backend_instance_3:
          hosts:
            backend_3:
              ansible_host: 10.0.64.20
    database:
      vars:
        ansible_port: 22
        ansible_user: ubuntu
        ansible_ssh_common_args: >-
          -o ProxyCommand="ssh -W %h:%p -q ubuntu@13.36.46.172" -o
          StrictHostKeyChecking=no
      children:
        database_instance_1:
          hosts:
            database_1:
              ansible_host: 10.0.0.30
    monitor:
      vars:
        ansible_port: 22
        ansible_user: ubuntu
        ansible_ssh_common_args: >-
          -o ProxyCommand="ssh -W %h:%p -q ubuntu@13.36.46.172" -o
          StrictHostKeyChecking=no
      children:
        monitor_instance:
          hosts:
            monitor_1:
              ansible_host: 10.0.0.40
    bastion:
      vars:
        ansible_port: 22
        ansible_user: ubuntu
      children:
        bastion_instance:
          hosts:
            bastion_1:
              ansible_host: 13.36.46.172
